### ISSUE TITLE
engine/Model class Undefined PORT constant

### ISSUE THREAD

**Issue by chr1974** [davidjconnelly/trongate-framework#101]
In the engine/Model.php class __construct method
you are defining:

`$this->port = (defined('PORT') ? PORT : '3306')`

but the PORT after ? is not defined anywhere, guess it should be defined in the config/database.php?

**Comment by DaFa66** [comment]
Hi Christain,

PORT is defined in config/database.php which is loaded via .htaccess > index.php in the public folder

```
<?php
require_once '../engine/bootstrap.php';

//Init Core Library
$init = new Core;
```

This in turn instantiates:
```
<?php
session_start();
require_once '../config/config.php';
require_once '../config/custom_routing.php';
require_once '../config/database.php';
require_once '../config/site_owner.php';
require_once '../config/themes.php';
require_once 'get_segments.php';
```
Thus, PORT is defined here, before the Model class is instantiated on line 25 in Trongate.php:
```
<?php
//Database settings
define('HOST', '127.0.0.1');
define('PORT', '3306');
define('USER', 'root');
define('PASSWORD', '');
define('DATABASE', 'your_app');
```
In the early days, the PORT was set at 3306 by default and there was no way to change it.  Later, I can't recall when but maybe you can find it in the commit history; we added the ability to change port numbers.

Initially, it was declared as:
`$this->port = '3306';`
and
`define('PORT', '3306');`
was not defined in database.php
and later a ternary was added, so if PORT was empty:
`$this->port = (defined('PORT') ? PORT : '3306');`
with the addition of:
`define('PORT', '3306');`
in database.php

To test the above out you can drop a die(PORT); in the constructor of Model.php
```
    public function __construct($current_module = NULL) {

        die(PORT);

        $this->port = (defined('PORT') ? PORT : '3306');
```
After testing this myself, if 'PORT' is defined but empty '', the above will work but if 'PORT' wasn't defined in database.php it would error out, thus this could be an alternative approach:

**`$this->port = (array_key_exists('PORT', get_defined_constants()) && PORT !== '' ? PORT : '3306');`**

This would allow for ('PORT' defaulting to '3306' if not defined or an empty string, otherwise 'PORT' will equal whatever is defined in database.php)
```
<?php
//Database settings
define('HOST', '127.0.0.1');
// define('PORT', '');
define('USER', 'root');
define('PASSWORD', '');
define('DATABASE', 'b2');
```
**result $this->port = '3306'.**  Yes, Intelephense will complain with a red squiggly underline on 'PORT' as `Undefined constant 'PORT'.intelephense` but PHP will not error out
```
<?php
//Database settings
define('HOST', '127.0.0.1');
// define('PORT', '3307');
define('USER', 'root');
define('PASSWORD', '');
define('DATABASE', 'b2');
```
**result $this->port = '3307'.**

**Comment by chr1974** [comment]
ok, i see, i just wondered since i did not see PORT define in config file.
