### ISSUE TITLE
Its January the 14th 2021... 

### ISSUE THREAD

**Issue by LinearThinker** [davidjconnelly/trongate-framework#29]
Planets are circling stars, dinosaurs are fornicating throughout the heavens, black holes are forming, we now have gravitational waves to solve all of the heavenly mysteries, Leftists are taking over the world, Globalists are their puppet masters, and Democracy has begun to circle the drain, so... 

**Is Trongate now ready for prime time, yet?  Is the latest version on Github a version that can be used for a live application?**
**Where to address our emails to David J Connelly? I confess, this should have been an email, I tried, but without an email address, it would end up in a void and never read. Or... I would get some glib response that is more enraging than being ignored.  
David!!  Where are you? From what little I can see of you on YouTube, you look a little worn out.**

YES, its true! I'm not ready to relinquish to the desk top app.  What does the API manager do?? All that SQL for use with the API manager, what does it do?

**Comment by davidjconnelly** [comment]
I'm really glad that people are using the bug request feature to remind me that I'm looking a little bit worn out.  That's PRECISELY what I had hoped for when I launched it.  Just TELL THE WORLD some bullschitt about your opinion on how I look and then submit it as a bug request so that anyone thinking about using the framework can see that it has a bug.  Thanks a schitt.  Thanks a bloody schitt.  PS: fuck.

**Comment by LinearThinker** [comment]
Are things going well with Trongate? Last I looked, it was looking very promising.
