### ISSUE TITLE
TYPEERROR: CONN.QUERY IS NOT A FUNCTION

### ISSUE THREAD

**Issue by lordadamson** [davidjconnelly/trongate-framework#46]
![Screenshot from 2021-07-05 22-21-08](https://user-images.githubusercontent.com/43860544/124516537-2e0ec780-dde2-11eb-91f3-ad7bca594140.png)

I don't know if this is the place to report the issue but I did not find a repo for the desktop app.

Same issue happened on both Ubuntu 20.04 and MacOS big sur.

Steps to reproduce (on ubuntu 20.04):
- In the mysql prompt:
```
create user trongate_user@localhost idenified by 'qwertyuiop';
create database trongate;
grant all privileges on trongate.* to 'trongate_user'@'localhost';
flush privileges;
exit
```

In the Trongate App:
- Create New App
- New Trongate App
- Enter App Name: 'app'
- Leave default url: 'http://localhost/app/'
```json
{
    "host" : "127.0.0.1",
    "user" : "trongate_user",
    "password" : "qwertyuiop",
    "database" : "trongate"
}
```
- `TYPEERROR: CONN.QUERY IS NOT A FUNCTION`
My Environment:
- Ubuntu 20.04
- I have php 7.4 installed
- I have mysql 8.0.25
- I have apache 2.4.41 (with php-mod enabled)

**Comment by davidjconnelly** [comment]
This one is a little bit scary for me.  I had that error about two months ago and - for reasons that I don't entirely understand - it just went away.

I'll try to recreate this and then get back to you.

**Comment by lordadamson** [comment]
It happens consistently with me. I could help debug it if you want. But I don't have the source code of the application. Let me know if you want me to do anything.

**Comment by davidjconnelly** [comment]
Test

**Comment by lordadamson** [comment]
Are you testing replies from the email? 😂 
I mean it's working, so that's good hahah

**Comment by davidjconnelly** [comment]
Oh dear.  I apologise.  I was out walking by the riverside last night and I wasn't entirely sure if dealing with this on my phone was the way to go.

This issue you've raised is a concern.

How would you feel about meeting up on Skype at a time of your choosing, to go over this?  It would give me an opportunity to see what you're seeing and - of course - I'd be glad to show you the code.

**Comment by lordadamson** [comment]
Sure! I believe we have close time-zones so that's good.

How about today at 5pm (GMT+0)?

I haven't had Skype in a long time, but I can install it. If you already have zoom, that would be a lot better.

Anyway here's my Skype: adham.zahran@hotmail.com

**Comment by Adamanthus** [comment]
Would be nice to see this fixed, also consistent on Windows (Bitnami Wampstack which uses MySQL, not MariaDB, though I doubt this makes a difference it may).

**Comment by davidjconnelly** [comment]
Hi. My Skype ID is david.webguy .  Please do add me, when you can.  

Would it be possible to arrange a concrete date and time?   I'm available any time/day on or after this Wedneday.

**Comment by DaFa66** [comment]
Hi guys,

DC designed the Desktop app to create a database of the same name as the
app, unless you specify otherwise, but if a database exists it won't
proceed and you should see an error message telling you that.  Also,
creating a new user with privileges to a specific database that already
exists won't work unless you raise that user to root level so the Desktop
app can then create the database for you:
GRANT USAGE ON *.* TO 'trongate_user'@'localhost' IDENTIFIED BY
'qwertyuiop';

I would instead do the following if this is the way you want it to work as
you intended:

Open the Trongate Desktop App:

   - Create New App
   - New Trongate App
   - Enter App Name: 'app'
   - Leave default url: 'http://localhost/app/'

{
    "host" : "127.0.0.1",
    "user" : "root",
    "password" : "",
    "database" : "trongate"
}

Choose a location > htdocs for me it is 'D:\xampp\htdocs"

Clicking 'GENERATE NEW APP" should now work and a directory called 'app'
should now exist in htdocs and a database named 'trongate' should exist.
Don't click the 'VIEW YOUR NEW APP' just yet, well you can as it will work
with 'root' no password, but wait until we create a new user and assign
privileges to the database.

Navigate to your new app, mine is located at 'D:\xampp\htdocs\app' then
open with your favourite text editor and load in the 'database.php' file
from the 'config' folder.

Change it to read as:
<?php
//Database settings
define('HOST', '127.0.0.1');
define('USER', 'trongate_user');
define('PASSWORD', 'qwertyuiop');
define('DATABASE', 'trongate');

Open a terminal (Change directory to your MYSQL bin folder or not necessary
if it's in your path) (I'm on Windows) or open PHPMyAdmin and execute the
SQL from there:

> mysql.exe -uroot -p

> CREATE USER ***@***.*** IDENTIFIED BY 'qwertyuiop';
> GRANT ALL PRIVILEGES ON trongate.* TO 'trongate_user'@'localhost';
> FLUSH PRIVILEGES;
> exit

[image: image.png]

Now click on 'View Your App'
[image: image.png]

It totally works!
[image: image.png]

Ciao for now!

**Comment by davidjconnelly** [comment]
Okay.  Many thanks to Simon for figuring this one out.  Although we were not able recreate the error, we're pretty sure about what has happened here.  In short, this was a fall at the first hurdle.  

If you look at the steps that were written on the first thread, you'll notice that a database was manually created.  This is not the correct  procedure.  When you generate a new app with the Trongate Desktop App, it will create the database for you.  So, if you try this again but _without_ creating the database then I'm sure you'll be good to go.

I'm going to close this for the moment but you are welcome to reopen if you require more assistance.  Many thanks again to Simon for this one.

**Comment by KevinBlakeLopez** [comment]
Hello David,
I just recently had this same issue when I installed Trongate on my 2015 Macbook Air.  I didn't try to create any databases via PHPmyAdmin.  I just got this same error message when trying to create a new App right from the get go.  I'm looking forward to creating apps with Trongate!
Thanks,
Kevin

**Comment by kivison** [comment]
I have been looking at Trongate for a few months and really want to give it a go. I have installed the desktop app and I got this when trying to create an app (software just updated to most recent version of trongate). The db doesnt exist and I have tried all manner of permutations. I user MAMP PRO on a Mac (obviously) the mysql command access is /Applications/MAMP/Library/bin/mysql I dont know if this is an issue when trying to create a db, I have tried creating a db to link to, using all the same syntax (app app name and app as db etc) and without (leaving trongate to make everything) but always get the same issue.

**Comment by EpicDevNL** [comment]
Had the same issue. Fixed it by creating a new user in mysql like this:
mysql> CREATE USER 'admin'@'localhost'; GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';

When creating new app, only change username to admin and it should work. 

This also works:

-ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
 
change password to something else


-refresh privileges:

FLUSH PRIVILEGES;

**Comment by talib1996** [comment]
For me it was due to the fact that my XAMPP Database Server's port no was set to 4431 whereas while creating a new app  via Trongate Desktop , I did not change the port number from 3306 to 4431.
I just changed my port no 3306 to 4431 and it worked as God willing.    :)

**Comment by skilleven** [comment]
Just my 2 cents: had the same issue using MAMP on mac not knowing that MAMP (other than XAMPP) has a standard password for the DB. user: root / pass: root
