### ISSUE TITLE
Problem with modals using bootstrap

### ISSUE THREAD

**Issue by AlexTheCynic** [davidjconnelly/trongate-framework#84]
Hello, im using the admin template but if i try to style the create form with bootstrap the delete record modal doesnt work anymore. 
Looks like admin.css and bootstrap.css are using the same name for the modal class and maybe thats the problem.
Is there a way to have them both? 
I tried to use the !important rule but with no success.

**Comment by davidjconnelly** [comment]
Bootstrap like Laravel, like Symfony and like every JavaScript framework known to humanity gets rewritten frequently and with no obvious benefit to the end user.  Do you SERIOUSLY think I'm going to waste a solitary minute getting Bootstrap to work with the Trongate code generator when I'm GUARANTEED to have the whole thing breaking the moment they come out with another pointless version?

What kind of an idiot would I be to waste my time with such a venture?

Trongate is v1 forever.  Bootstrap looks nice but it's not v1 forever.  

I'm disappointed that you tarnished the good name of Trongate by posting this as an issue, here on the GitHub page.  

I suggest you go to the makers of Bootstrap and leave an issue there.  Tell them to stop rewriting their code.

The moment Bootstrap becomes v1 forever then I'll make it work with the Trongate code generator.  Until then don't come to me with a fault declaration because of some frequently rewritten third party bullschitt.

If you are determined to use Bootstrap then that's okay but it's not going to work with Trongate auto-genrerated code.  That's Bootstrap's fault.  Not Trongate's.

**Comment by AlexTheCynic** [comment]
Looks like you wasted more than one minute to rant about the same thing we already heard many times.
But you, and not me bragged about the freedom to use other libraries like bootstrap. And looks like others in the module market are using the useless bootstrap too.
You shouldnt scare away ppl for wanting to use libraries that have features your frameworks doesnt! Not everyone has the time to learn everything from scratch.
Wait a minute, it is exactly to these ppl that the framework should be aimed to, but lets make fun of them. Its gonna be good

**Comment by davidjconnelly** [comment]
Phuck off.  Just phuck off.

This message was not written by David Connelly but by his new public
relations manager.
